# .github/workflows/validate-and-deploy.yml
name: Domain Validation and DNS Update

on:
  pull_request:
    branches: [main]
    paths: ['domains/**']
  push:
    branches: [main]
    paths: ['domains/**']

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  validate:
    name: Validate Domain Files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies (if package.json exists)
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No package.json found, skipping npm install"
          fi
        
      - name: Run validation
        run: node scripts/validate.js
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        
      - name: Comment on PR - Success
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ **Validation passed!** Your domain registration looks good.\n\n🔍 **Awaiting manual review** - A maintainer will review and merge your PR soon.'
            })
        
      - name: Comment on PR - Failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Domain validation failed!**\n\nPlease check the errors in the workflow logs above and fix your JSON file(s). Common issues:\n\n- Invalid JSON format\n- GitHub username doesn\'t match PR author\n- Invalid email address\n- Invalid CNAME target\n- Reserved subdomain name\n- User exceeds domain limit\n\nFix the issues and push again for automatic re-validation.'
            })

  deploy:
    name: Update DNS Records
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies (if package.json exists)
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No package.json found, skipping npm install"
          fi
        
      - name: Update Cloudflare DNS
        run: node scripts/deploy.js
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          DOMAIN_NAME: loves-to.dev
