name: Domain Validation and DNS Update

on:
  pull_request:
    branches: [main]
    paths: ['domains/**']
  push:
    branches: [main]
    paths: ['domains/**']

jobs:
  validate:
    name: Validate Domain Files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Run validation
        run: node scripts/validate.js
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}

  deploy:
    name: Update DNS Records
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Update Cloudflare DNS
        run: node scripts/deploy.js
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          DOMAIN_NAME: loves-to.dev
